#teste market place
name: 'My GitHub Action LULY'
description: 'A brief description of my action'
inputs:
  exampleInput:
    description: 'An example input'
    required: true
    default: 'default value'
outputs:
  exampleOutput:
    description: 'An example output'
runs:
  using: 'node12'
  main: 'index.js'
